services:
  mysql:
    image: mysql:${MYSQL_VERSION:-8.4}
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-snippet_box}
      MYSQL_USER: ${MYSQL_USER:-snippet_box}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-SnippetBox!2026}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-SnippetBox!2026}
    volumes:
      - snippet-box-data:/var/lib/mysql:rw

volumes:
  snippet-box-data: